services:
  ###################################################
  # Service: reverse proxy
  ###################################################
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  ###################################################
  # Service: backend
  ###################################################
  backend:
    build: "backend/."
    ports:
      - "3000:3000"
    env_file: "../secrets.env"
    develop:
      watch:
        - path: ./backend/
          action: sync
          target: /usr/local/app/src
        - path: ./backend/package.json
          action: rebuild
    depends_on:
      - redis

  ###################################################
  # Service: client
  ###################################################
  frontend:
    build: "frontend/."
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /usr/local/app/src
        - path: ./client/package.json
          action: rebuild
  ###################################################
  # Service: redis
  ###################################################
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  ###################################################
  # Service: phpmyadmin
  ###################################################
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
