name: Run Playwright Tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: local
      # Provide environment variables from GitHub Secrets (adjust names as needed)
      MADDOX_MYSQL_SERVER: ${{ secrets.MADDOX_MYSQL_SERVER }}
      MADDOX_MYSQL_USERNAME: ${{ secrets.MADDOX_MYSQL_USERNAME }}
      MADDOX_MYSQL_PASSWORD: ${{ secrets.MADDOX_MYSQL_PASSWORD }}
      MADDOX_MYSQL_DB: ${{ secrets.MADDOX_MYSQL_DB }}
      MADDOX_MYSQL_PORT: ${{ secrets.MADDOX_MYSQL_PORT }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      MATHPIX_API_KEY: ${{ secrets.MATHPIX_API_KEY }}
      MATHPIX_APP_ID: ${{ secrets.MATHPIX_APP_ID }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      QUACKPREP_EMAIL_USER: ${{ secrets.QUACKPREP_EMAIL_USER }}
      QUACKPREP_EMAIL_PASS: ${{ secrets.QUACKPREP_EMAIL_PASS }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install; npx playwright install;

      - name: Start application
        run: |
          # Start the dev server in the background
          npm run dev &

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000 http://localhost:3001 --timeout 240000

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload test artifacts
        if: always() # Upload artifacts even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            test-results/
            playwright-report/
